### ISSUE TITLE
What scope is required for the github access token?

### ISSUE THREAD

**Issue by franz-see** [IgnusG/jest-report-action#100]

**Comment by IgnusG** [comment]
You can either use the, by default provided GitHub generated secret `secrets.GITHUB_TOKEN` or if you do want to use your own token the `repo` scope should suffice

![image](https://user-images.githubusercontent.com/6438760/98485239-40b20c00-2215-11eb-8532-5f1084f178ec.png)

**Comment by IgnusG** [comment]
I assume this question was answered and will close it now. If you still have problems feel free to create a new issue
