### ISSUE TITLE
Getting this error Something went wrong: Error: ENOENT: no such file or directory, open 'XXX/XXX/junit.xml'

### ISSUE THREAD

**Issue by fahadshehzada** [IgnusG/jest-report-action#31]
##[error]Something went wrong: Error: ENOENT: no such file or directory, open 'XXX/XXX/junit.xml'

.yml file

- name: Jest Github Action Reporter
        uses: IgnusG/jest-report-action@v2.3.2
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISOLATED_MODE: 1
        with:
          test-command: ${{ matrix.service.dir }} && yarn test
          junit-file: junit.xml
          run-name: build
          check-name: Jest
          working-directory: ${{ matrix.service.dir }}

**Comment by IgnusG** [comment]
Hey @fahadshehzada!

The action looks for the junit file relative to the `working-directory` option, so it would be whatever `${{ matrix.service.dir }}/junit.xml` resolves to. 

In your case I assume `${{ matrix.service.dir }}` is XXX/XXX

The action expects therefore a folder structure similar to:
```
- XXX
  - XXX
    - junit.xml
    - src/dist/or other
```

Can you share an example how your file directory structure looks like?

**Comment by fahadshehzada** [comment]
I got the issue resolved by executing test before executing this action in .yml file

      - name: Yarn Test
        id: unit-test
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: cd ${{ matrix.service.dir }} && yarn test
        env:
          ISOLATED_MODE: 1

and then call above action. It resolved my issue. test-command is only getting the test result not running the actual test.

**Comment by IgnusG** [comment]
Good to hear it works 😉 

Yeah, this package is designed to give you full freedom how and when you want jest to run. It only parses results and displays failed tests on GitHub
